LOGDIR: ''
DEVICE: 'cuda'
EXP_NAME: 'train_stage1'
OUTPUT_DIR: 'experiments/'
NUM_WORKERS: 8
MODEL_CONFIG: 'configs/yamls/model_base.yaml'
FLIP_EVAL: True
SEED_VALUE: 42

TRAIN:
  LR: 5e-4
  BATCH_SIZE: 64
  END_EPOCH: 100
  STAGE: 'stage1'
  CHECKPOINT: ''
  MILESTONES: [60, 80]

LOSS:
  SHAPE_LOSS_WEIGHT: 0.004
  JOINT3D_LOSS_WEIGHT: 0.4
  JOINT2D_LOSS_WEIGHT: 0.1
  POSE_LOSS_WEIGHT: 8.0
  CASCADED_LOSS_WEIGHT: 0.0
  SLIDING_LOSS_WEIGHT: 0.5
  CAMERA_LOSS_WEIGHT: 0.04
  ROOT_VEL_LOSS_WEIGHT: 0.001
  LOSS_WEIGHT: 50.0
  CAMERA_LOSS_SKIP_EPOCH: 5