LOGDIR: ''
DEVICE: 'cuda'
EXP_NAME: 'train_stage1'
OUTPUT_DIR: 'experiments/'
NUM_WORKERS: 8
MODEL_CONFIG: 'configs/yamls/model_base.yaml'
FLIP_EVAL: True
SEED_VALUE: 1

TRAIN:
  LR: 5e-4
  BATCH_SIZE: 64
  END_EPOCH: 100
  STAGE: 'stage1'
  CHECKPOINT: ''

LOSS:
  SHAPE_LOSS_WEIGHT: 0.004
  JOINT3D_LOSS_WEIGHT: 0.4
  JOINT2D_LOSS_WEIGHT: 0.1
  POSE_LOSS_WEIGHT: 8.0
  CASCADED_LOSS_WEIGHT: 0.0
  LOSS_WEIGHT: 50.0