LOGDIR: ''
DEVICE: 'cuda'
EXP_NAME: 'train_stage2'
OUTPUT_DIR: 'experiments'
NUM_WORKERS: 8
MODEL_CONFIG: 'configs/yamls/model_base.yaml'
FLIP_EVAL: True
SEED_VALUE: 42

TRAIN:
  LR: 1e-4
  LR_FINETUNE: 1e-5
  STAGE: 'stage2'
  CHECKPOINT: 'checkpoints/wham_stage1.pth.tar'
  BATCH_SIZE: 64
  END_EPOCH: 40
  MILESTONES: [20, 30]
  LR_DECAY_RATIO: 0.2

MODEL:
  BACKBONE: 'vit'

LOSS:
  SHAPE_LOSS_WEIGHT: 0.0
  JOINT2D_LOSS_WEIGHT: 3.0
  JOINT3D_LOSS_WEIGHT: 6.0
  POSE_LOSS_WEIGHT: 1.0
  CASCADED_LOSS_WEIGHT: 0.05
  SLIDING_LOSS_WEIGHT: 0.5
  CAMERA_LOSS_WEIGHT: 0.01
  ROOT_VEL_LOSS_WEIGHT: 0.001
  LOSS_WEIGHT: 60.0
  CAMERA_LOSS_SKIP_EPOCH: 0

DATASET:
  SEQLEN: 81
  RATIO: [0.2, 0.2, 0.2, 0.2, 0.2]